version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@aws-blocks/*"
  - package-ecosystem: npm
    directory: "/aws-blocks"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "@aws-blocks/*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
